-- ================================================================================
-- INTERVIEW PREP: BikeStores Database - 15 Beginner-Friendly Questions
-- Focus: Basic SELECT, WHERE, JOIN, GROUP BY, Simple Window Functions
-- Difficulty: Beginner to Lower-Intermediate
-- ================================================================================

-- ================================================================================
-- QUESTION 1: Basic SELECT (Beginner)
-- ================================================================================
--
-- "Show all products from the production.products table.
--  Display only: product_name, model_year, list_price.
--  Order by list_price from highest to lowest."
--
-- ================================================================================

-- ================================================================================
-- QUESTION 2: Filtering with WHERE (Beginner)
-- ================================================================================
--
-- "Find all customers who live in New York (state = 'NY').
--  Show their first name, last name, city, and state."
--
-- ================================================================================

-- ================================================================================
-- QUESTION 3: Simple JOIN (Beginner)
-- ================================================================================
--
-- "Show all orders with customer names.
--  Display: order_id, order_date, customer first name, customer last name.
--  Order by order_date (newest first)."
--
-- ================================================================================

-- ================================================================================
-- QUESTION 4: Basic GROUP BY with COUNT (Beginner)
-- ================================================================================
--
-- "Count how many customers are in each state.
--  Show state name and number of customers.
--  Order by customer count from highest to lowest."
--
-- ================================================================================

-- ================================================================================
-- QUESTION 5: GROUP BY with SUM (Beginner-Intermediate)
-- ================================================================================
--
-- "Calculate total sales amount for each store.
--  Show store_name and total_sales.
--  (Hint: sales_amount = quantity * list_price * (1 - discount))"
--
-- ================================================================================

-- ================================================================================
-- QUESTION 6: GROUP BY with AVG and HAVING (Beginner-Intermediate)
-- ================================================================================
--
-- "Find brands that have an average product price greater than $2000.
--  Show brand_name and average_price.
--  Only include brands with at least 3 products."
--
-- ================================================================================

-- ================================================================================
-- QUESTION 7: Basic Window Function - ROW_NUMBER() (Intermediate)
-- ================================================================================
--
-- "Number all products from cheapest to most expensive.
--  Show product_name, list_price, and a row number column called 'price_rank'.
--  Cheapest product should be number 1."
--
-- ================================================================================

-- ================================================================================
-- QUESTION 8: ROW_NUMBER() with PARTITION BY (Intermediate)
-- ================================================================================
--
-- "For each brand, number the products by price (most expensive first).
--  Show brand_name, product_name, list_price, and rank within brand.
--  The most expensive product in each brand should be number 1."
--
-- ================================================================================

-- ================================================================================
-- QUESTION 9: Basic Running Total with SUM() OVER() (Intermediate)
-- ================================================================================
--
-- "Calculate a running total of daily orders.
--  Show order_date, number of orders on that date, 
--  and cumulative total of orders so far.
--  Order by order_date."
--
-- ================================================================================

-- ================================================================================
-- QUESTION 10: RANK() vs ROW_NUMBER() (Intermediate)
-- ================================================================================
--
-- "Use both ROW_NUMBER() and RANK() on products ordered by list_price DESC.
--  Show product_name, list_price, row_number, and rank.
--  What difference do you notice when there are ties?"
--
-- ================================================================================

-- ================================================================================
-- QUESTION 11: Multiple JOINs (Intermediate)
-- ================================================================================
--
-- "Show all order items with product and order information.
--  Display: order_id, order_date, product_name, quantity, list_price.
--  Only show orders from 2023."
--
-- ================================================================================

-- ================================================================================
-- QUESTION 12: Basic CASE Statement (Intermediate)
-- ================================================================================
--
-- "Categorize products by price:
--    Under $500 = 'Budget'
--    $500 to $2000 = 'Regular'
--    Over $2000 = 'Premium'
--  Show product_name, list_price, and price_category."
--
-- ================================================================================

-- ================================================================================
-- QUESTION 13: LAG() - Previous Row Access (Intermediate)
-- ================================================================================
--
-- "For each customer, show their order date and the date of their previous order.
--  Display: customer_id, order_id, order_date, previous_order_date.
--  If no previous order, show NULL."
--
-- ================================================================================

-- ================================================================================
-- QUESTION 14: Finding Top N with Window Function (Intermediate)
-- ================================================================================
--
-- "Find the top 3 most expensive products in each category.
--  Show category_name, product_name, list_price, and rank.
--  Use RANK() for ranking."
--
-- ================================================================================

-- ================================================================================
-- QUESTION 15: Combined Query - Everything Learned (Intermediate)
-- ================================================================================
--
-- "Create a report showing:
--    1. Customer name
--    2. Total amount spent by that customer
--    3. Customer's rank by spending (1 = highest spender)
--    4. Price tier of customer (VIP if spent > $5000, Regular if $1000-$5000, New if < $1000)
--  Order by rank."
--
-- ================================================================================

-- ================================================================================
-- END OF INTERVIEW QUESTIONS
-- ================================================================================
